[package]
name = "rsyncer_core"
version = "0.12.0"
edition = "2024"
rust-version = "1.92.0"
description = "Sync liked tracks from Spotify to Last.fm"
license = "MIT"
repository = "https://github.com/nickmetal/lastfm-spotify-syncer"
keywords = ["spotify", "lastfm", "music", "sync"]
categories = [
    "command-line-utilities",
    "music-playlist-syncing",
    "network-programming",
]


[dependencies]
async-trait = "0.1.89"
futures = "0.3.31"
futures-util = "0.3.31"
lastfm-rust = "0.1.0"
log = "0.4.33"
rand = "0.10.2"
rspotify = { version = "0.16.1", features = ["cli"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.17"
dirs = "6.0.0"
