test:
  cargo llvm-cov --summary-only --features cli

lint:
  cargo clippy --all-targets --features cli -- -D warnings

build-api:
  cargo build --release --bin http_api

build-cli:
  cargo build --release --bin rsyncer --features cli

docker-build:
  #!/usr/bin/env bash
  VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
  echo "Building rsyncer-api:$VERSION"
  docker build --build-arg VERSION=$VERSION -t rsyncer-api:$VERSION .

docker-run:
  #!/usr/bin/env bash
  VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
  echo "Running rsyncer-api:$VERSION"
  docker run --rm -it rsyncer-api:$VERSION -p 8080:8080 --name rsyncer-api

bump-minor:
    cargo set-version --bump minor
